<?php

$uri = get_template_directory_uri() . '/liquid/assets/img/demos/';

// Demos
$demos = array(

	'original' => array(
		'title'       => esc_html__( 'Original', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'original.jpg',
		'preview'     => 'http://original.liquid-themes.com',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'agency' => array(
		'title'       => esc_html__( 'Agency', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'agency.jpg',
		'preview'     => 'http://agency.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'architecture' => array(
		'title'       => esc_html__( 'Architecture', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'architecture.jpg',
		'preview'     => 'http://architecture.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'beauty' => array(
		'title'       => esc_html__( 'Beauty', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'beauty.jpg',
		'preview'     => 'http://beauty.liquid-themes.com',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'blockchain' => array(
		'title'       => esc_html__( 'Blockchain', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'blockchain.jpg',
		'preview'     => 'http://blockchain.liquid-themes.com',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'blog-grid' => array(
		'title'       => esc_html__( 'Blog Grid', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'blog-grid.jpg',
		'preview'     => 'http://blog-grid.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'blogger' => array(
		'title'       => esc_html__( 'Blogger', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'blogger.jpg',
		'preview'     => 'http://blogger.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'blog-masonry' => array(
		'title'       => esc_html__( 'Blog Masonry', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'blog-masonry.jpg',
		'preview'     => 'http://blog-masonry.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'business' => array(
		'title'       => esc_html__( 'Business', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'business.jpg',
		'preview'     => 'http://business.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'charity' => array(
		'title'       => esc_html__( 'Charity', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'charity.jpg',
		'preview'     => 'http://charity.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'contemporary' => array(
		'title'       => esc_html__( 'Contemporary', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'contemporary.jpg',
		'preview'     => 'http://contemporaryshop.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'concept' => array(
		'title'       => esc_html__( 'Concept', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'concept.jpg',
		'preview'     => 'http://conceptshop.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'retailer' => array(
		'title'       => esc_html__( 'Retailer', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'retailer.jpg',
		'preview'     => 'http://retail.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'minimalshop' => array(
		'title'       => esc_html__( 'Minimal Shop', 'ave' ),
		'description' => '',
		'screenshot'  => $uri . 'minimalshop.jpg',
		'preview'     => 'http://minimalshop.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'services' => array(
		'title'       => esc_html__( 'Services', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'services.jpg',
		'preview'     => 'http://services.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'construction' => array(
		'title'       => esc_html__( 'Construction', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'construction.jpg',
		'preview'     => 'http://construction.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'creative' => array(
		'title'       => esc_html__( 'Creative', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'creative.jpg',
		'preview'     => 'http://creative.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'cryptocurrency' => array(
		'title'       => esc_html__( 'Crypto Currency', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'crypto-currency.jpg',
		'preview'     => 'http://cryptocurrency.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'digitalcreative' => array(
		'title'       => esc_html__( 'Digital Creative', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'digital-creative.jpg',
		'preview'     => 'http://digitalcreative.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'education' => array(
		'title'       => esc_html__( 'Education', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'education.jpg',
		'preview'     => 'http://education.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'digitalagency' => array(
		'title'       => esc_html__( 'Digital Agency', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'digital-agency.jpg',
		'preview'     => 'http://digitalagency.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'freelancer' => array(
		'title'       => esc_html__( 'Freelancer', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'freelancer.jpg',
		'preview'     => 'http://freelancer.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'global' => array(
		'title'       => esc_html__( 'Global', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'global.jpg',
		'preview'     => 'https://global.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'gym' => array(
		'title'       => esc_html__( 'Gym', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'gym.jpg',
		'preview'     => 'http://gym.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'landing' => array(
		'title'       => esc_html__( 'Landing', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'landing.jpg',
		'preview'     => 'http://landing.liquid-themes.com',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'hotel' => array(
		'title'       => esc_html__( 'Hotel', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'hotel.jpg',
		'preview'     => 'http://hotel.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'multi-concept' => array(
		'title'       => esc_html__( 'Multiconcept', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'multi-concept.jpg',
		'preview'     => 'http://multiconcept.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'magazine' => array(
		'title'       => esc_html__( 'Magazine', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'magazine.jpg',
		'preview'     => 'http://magazine.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'medical' => array(
		'title'       => esc_html__( 'Medical', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'medical.jpg',
		'preview'     => 'http://medical.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'opus-1' => array(
		'title'       => esc_html__( 'Opus', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'opus-1.jpg',
		'preview'     => 'http://opus.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'opus-2' => array(
		'title'       => esc_html__( 'Opus 2', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'opus-2.jpg',
		'preview'     => 'http://opus-two.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'opus-3' => array(
		'title'       => esc_html__( 'Opus 3', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'opus-3.jpg',
		'preview'     => 'http://opus-three.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'opus-4' => array(
		'title'       => esc_html__( 'Opus 4', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'opus-4.jpg',
		'preview'     => 'http://opus-four.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'personal' => array(
		'title'       => esc_html__( 'Personal', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'personal.jpg',
		'preview'     => 'http://personal.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'minimal-magazine' => array(
		'title'       => esc_html__( 'Minimal Magazine', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'minimal-magazine.jpg',
		'preview'     => 'http://minimal-magazine.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'portfolio-dynamic' => array(
		'title'       => esc_html__( 'Portfolio Dynamic', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'portfolio-dynamic.jpg',
		'preview'     => 'http://portfolio-dynamic.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'avantgarde' => array(
		'title'       => esc_html__( 'Avantgarde', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'avantgarde.jpg',
		'preview'     => 'http://avantgarde.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'portfolio-grid' => array(
		'title'       => esc_html__( 'Portfolio Grid', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'portfolio-grid.jpg',
		'preview'     => 'http://portfolio-grid.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'portfolio-masonry' => array(
		'title'       => esc_html__( 'Portfolio Masonry', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'portfolio-masonry.jpg',
		'preview'     => 'http://portfolio-masonry.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'portfolio-modern' => array(
		'title'       => esc_html__( 'Portfolio Modern', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'portfolio-modern.jpg',
		'preview'     => 'http://portfolio-modern.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'portfolio' => array(
		'title'       => esc_html__( 'Portfolio', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'portfolio.jpg',
		'preview'     => 'http://portfolio.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'rtl' => array(
		'title'       => esc_html__( 'RTL', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'rtl.jpg',
		'preview'     => 'http://rtl.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'mobile' => array(
		'title'       => esc_html__( 'Mobile', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'mobile.jpg',
		'preview'     => 'http://mobile.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'shop' => array(
		'title'       => esc_html__( 'Shop', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'shop.jpg',
		'preview'     => 'http://shop.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'stack' => array(
		'title'       => esc_html__( 'Stack', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'stack.jpg',
		'preview'     => 'http://stack.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'travel' => array(
		'title'       => esc_html__( 'Travel', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'travel.jpg',
		'preview'     => 'http://travel.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'virtus-1' => array(
		'title'       => esc_html__( 'Virtus', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'virtus-1.jpg',
		'preview'     => 'http://virtusone.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'virtus-2' => array(
		'title'       => esc_html__( 'Virtus 2', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'virtus-2.jpg',
		'preview'     => 'http://virtustwo.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'virtus-3' => array(
		'title'       => esc_html__( 'Virtus 3', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'virtus-3.jpg',
		'preview'     => 'http://virtusthree.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'virtus-4' => array(
		'title'       => esc_html__( 'Virtus 4', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'virtus-4.jpg',
		'preview'     => 'http://virtusfour.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'portrait' => array(
		'title'       => esc_html__( 'Portrait', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'portrait.jpg',
		'preview'     => 'http://portrait.liquid-themes.com',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'photographer' => array(
		'title'       => esc_html__( 'Photographer', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'photographer.jpg',
		'preview'     => 'http://photographer.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
		'saas' => array(
		'title'       => esc_html__( 'Saas', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'saas.jpg',
		'preview'     => 'http://saas.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
		'seo' => array(
		'title'       => esc_html__( 'Seo', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'seo.jpg',
		'preview'     => 'http://seo.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
		'candy' => array(
		'title'       => esc_html__( 'Candy', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'candy.jpg',
		'preview'     => 'http://candy.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
		'restaurant' => array(
		'title'       => esc_html__( 'Restaurant', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'restaurant.jpg',
		'preview'     => 'http://restaurant.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
		'lookbook' => array(
		'title'       => esc_html__( 'Lookbook', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'lookbook.jpg',
		'preview'     => 'http://lookbook.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'voguish' => array(
		'title'       => esc_html__( 'Voguish', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'voguish.jpg',
		'preview'     => 'http://voguish.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),
	'wave' => array(
		'title'       => esc_html__( 'Wave', 'ave' ),	
		'description' => '',
		'screenshot'  => $uri . 'wave.jpg',
		'preview'     => 'http://wave.liquid-themes.com/',
        'has_yellow'  => false,
		'has_widgets' => true,
	),

);